chore(cli): Refactor the CLI so parts of it can be used programmatically
deis/k8s-claimer pull request #91
Opened 2016-09-14 21:18 UTC by krancour

cc @arschles

2016-09-14 21:20 UTC, krancour commented on cli/client/errors.go
> -
fwiw, the reason I deleted these was that in the _only_ place(s) each of them was used, we were immediately doing a `log.Fatalf`. There isn't any sense returning a well-defined error when we always end execution before doing so (i.e. we don't).

2016-09-14 21:24 UTC, arschles commented on cli/client/create_lease.go
> +package client
not-blocking-for-this-PR-question: thoughts on moving this package to `./client`?

2016-09-14 21:25 UTC, krancour commented on cli/client/create_lease.go
> +package client
That would probably be an improvement. Happy to do that.

2016-09-14 23:21 UTC, krancour commented on cli/client/create_lease.go
> +package client
I did apply this change. I don't know why it's not showing up an an outdated diff. I think github needs to work some kinks out of this new review / comment system.

2016-09-15 18:29 UTC, arschles requested changes

2016-09-15 18:29 UTC, arschles commented on cli/client/delete_lease.go
> +		log.Fatalf("Error deleting. Code: %d, Body: %s", resp.StatusCode, string(bodyBytes))
don't fatally log here, so that a non-CLI client has a chance to handle the returned error

2016-09-15 18:29 UTC, arschles commented on cli/commands/create_lease.go
> +		// return errMissingAuthToken
can you just delete this? same for the below

2016-09-15 18:29 UTC, arschles commented on cli/commands/create_lease.go
> +		// return errMissingServer
delete this

2016-09-15 18:29 UTC, arschles commented on cli/commands/create_lease.go
> +		// return errMissingKubeConfigFile
delete this

2016-09-15 18:29 UTC, arschles commented on cli/commands/create_lease.go
> +		// return err
delete this

2016-09-15 18:29 UTC, arschles commented on cli/commands/create_lease.go
> +	resp, err := client.CreateLease(server, authToken, clusterVersion, clusterRegex, durationSec)
can you check this error

2016-09-15 18:29 UTC, arschles commented on client/create_lease.go
> +		return nil, fmt.Errorf("Error encoding request body (%s)", err)
can you create an error type for this

2016-09-15 18:29 UTC, arschles commented on client/create_lease.go
> +		return nil, fmt.Errorf("Error executing %s (%s)", endpt, err)
can you create an error type for this

2016-09-15 18:29 UTC, arschles commented on client/create_lease.go
> +		log.Fatalf("Error decoding response (%s)", err)
don't fatally log here so the caller of this function has a chance to handle the error

2016-09-15 18:29 UTC, arschles commented on client/delete_lease.go
> +		log.Fatalf("Error deleting. Code: %d, Body: %s", resp.StatusCode, string(bodyBytes))
don't fatally log here, so the caller has a chance to handle the error

2016-09-15 18:29 UTC, arschles approved these changes

2016-09-15 18:33 UTC, krancour commented on client/create_lease.go
> +		log.Fatalf("Error decoding response (%s)", err)
I think this line moved with the rest of this code from the cli's `commands` package and I accidentally did fix this. I will.

2016-09-15 18:33 UTC, krancour commented on client/delete_lease.go
> +		log.Fatalf("Error deleting. Code: %d, Body: %s", resp.StatusCode, string(bodyBytes))
I think this line moved with the rest of this code from the cli's commands package and I accidentally did fix this. I will.

2016-09-15 18:34 UTC, krancour commented on cli/commands/create_lease.go
> +	resp, err := client.CreateLease(server, authToken, clusterVersion, clusterRegex, durationSec)
Whoops. Good catch.

2016-09-15 21:15 UTC, arschles commented on client/create_lease.go
> +		return nil, fmt.Errorf("Error executing %s (%s)", endpt, err)
Can you create an error type for this?

2016-09-15 21:16 UTC, arschles commented on client/delete_lease.go
> +		log.Fatalf("Error executing %s (%s)", endpt, err)
don't fatally log here so that clients can handle the error instead of crashing

2016-09-15 21:17 UTC, arschles requested changes
Second review done

2016-09-16 17:29 UTC, merged